name: pi_car
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - pytorch
  - torchvision
  - pip:
    - opencv-python
    - requests
    - Pillow
    - PyYAML
    - matplotlib
    - pandas
    - keyboard
    - numpy
    - tqdm
    - seaborn
    - ipython
    - psutil
    - protobuf<=3.20.1
