name: app
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - pytorch
  - opencv
  - pip:
    - requests
    - matplotlib
    - pandas
    - keyboard
    - numpy
